"""role_add_title

Revision ID: 84149f0f3774
Revises: b0dbef7383df
Create Date: 2020-01-11 14:54:30.203682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84149f0f3774'
down_revision = 'b0dbef7383df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Role', sa.Column('title', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Role', 'title')
    # ### end Alembic commands ###
