"""role_rename_name_to_nick_name

Revision ID: a6ddad5f2693
Revises: af1bd1bb19b5
Create Date: 2020-01-11 15:09:42.845470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6ddad5f2693'
down_revision = 'af1bd1bb19b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Role', sa.Column('nick_name', sa.String(length=64), nullable=True))
    op.drop_index('name', table_name='Role')
    op.create_unique_constraint(None, 'Role', ['nick_name'])
    op.drop_column('Role', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Role', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    # 需要移除唯一约束，才能删除
    op.drop_constraint('nick_name', 'Role', type_='unique')
    op.create_index('name', 'Role', ['name'], unique=True)
    op.drop_column('Role', 'nick_name')
    # ### end Alembic commands ###
