"""role_add_height

Revision ID: af1bd1bb19b5
Revises: 84149f0f3774
Create Date: 2020-01-11 14:58:35.557833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af1bd1bb19b5'
down_revision = '84149f0f3774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Role', sa.Column('heigth', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Role', 'heigth')
    # ### end Alembic commands ###
